swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /anuncio:
    get:
      operationId: "app.vecinos.anuncio.read"
      tags:
        - "Anuncio"
      summary: "The anuncio data structure supported by the server application"
      description: "Read the list of anuncio"
      responses:
        200:
          description: "Successful read anuncio list operation"
          schema:
            type: "array"
            items:
              properties:
                titulo_anuncio:
                  type: "string"
                texto_anuncio:
                  type: "string"
                barrio:
                  type: "string"
                familia:
                  type: "string"
                fecha:
                  type: "string"
                